"""Snapshot Serengeti ALIA prompt banks.

Generated by carolyn_alia_dataset.ipynb (run once, then committed).
Other notebooks import this directly:

    from serengeti_prompts import PROMPT_VARIANTS, get_random_prompt
"""
from __future__ import annotations

import random

PROMPT_VARIANTS: dict[str, list[str]] = {
    "background": [
        "a camera trap photo of a {} in open grassland",
        "a camera trap photo of a {} in tall grass",
        "a camera trap photo of a {} near an acacia tree",
        "a camera trap photo of a {} in sparse shrubland",
        "a camera trap photo of a {} near a dry riverbed",
        "a camera trap photo of a {} near a watering hole",
        "a camera trap photo of a {} on a dirt game trail",
        "a camera trap photo of a {} in mixed woodland",
        "a camera trap photo of a {} in a savanna clearing",
        "a camera trap photo of a {} near rocky outcrops",
    ],
    "weather": [
        "a camera trap photo of a {} during heavy rain",
        "a camera trap photo of a {} during light rain",
        "a camera trap photo of a {} under overcast skies",
        "a camera trap photo of a {} after a rainstorm",
        "a camera trap photo of a {} during a thunderstorm",
        "a camera trap photo of a {} on a cloudy day",
        "a camera trap photo of a {} in dusty conditions",
        "a camera trap photo of a {} during strong winds",
        "a camera trap photo of a {} beneath dark storm clouds",
        "a camera trap photo of a {} in humid post-rain conditions",
    ],
    "lighting": [
        "a camera trap photo of a {} at sunrise",
        "a camera trap photo of a {} at sunset",
        "a camera trap photo of a {} at golden hour",
        "a camera trap photo of a {} in bright midday sunlight",
        "a camera trap photo of a {} under harsh afternoon light",
        "a camera trap photo of a {} at dawn",
        "a camera trap photo of a {} at dusk",
        "a nighttime infrared camera trap photo of a {}",
        "a low-light camera trap photo of a {} before sunrise",
        "a camera trap photo of a {} casting long evening shadows",
    ],
    "season": [
        "a camera trap photo of a {} during the dry season",
        "a camera trap photo of a {} during the wet season",
        "a camera trap photo of a {} at the start of the rainy season",
        "a camera trap photo of a {} at the end of the dry season",
        "a camera trap photo of a {} during peak green season",
        "a camera trap photo of a {} during seasonal drought",
        "a camera trap photo of a {} when vegetation is lush",
        "a camera trap photo of a {} when grass is dry and yellow",
        "a camera trap photo of a {} near a seasonal water source",
        "a camera trap photo of a {} during the wildebeest migration season",
    ],
}


def get_random_prompt(strategy: str, class_name: str) -> str:
    """Sample one prompt from *strategy* and fill in *class_name*."""
    return random.choice(PROMPT_VARIANTS[strategy]).format(class_name)
